// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel():Promise<void>;

export function Download(arg1:string):Promise<void>;

export function GetProxy():Promise<string>;

export function Parse(arg1:string):Promise<string>;

export function SetProxy(arg1:string):Promise<void>;
